x-common: &common
  restart: unless-stopped
  init: true
  security_opt:
    - no-new-privileges:true
  tty: true
  networks:
    - backend

name: Dyingstar-staging
services:
  webapp:
    <<: *common
    image: ghcr.io/dyingstar-game/discord-bot:staging
    pull_policy: always
    ports:
      - '8202:3000'
    env_file:
      - ./envs/staging.env
    read_only: true
    tmpfs:
      - /tmp
networks:
  backend:
    driver: bridge
