name: Build & Containerize Discord Bot

on:
  push:
    branches: [develop]
    # Push events for version tags (e.g. v1.2.3) will also trigger
    tags: ["v*"]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: sandbot
  REGISTRY: ghcr.io/dyingstar-game
